### ISSUE TITLE
Heads-up: UB due to misuse of mem::zeroed will soon lead to panic

### ISSUE THREAD

**Issue by RalfJung** [bodoni/truetype#10]
[Here](https://github.com/bodoni/truetype/blob/6da06be224c7ddb96a31db1e8c915ca87f3fc420/src/macros.rs#L64), this crate causes UB by ["Producing an invalid value"](https://doc.rust-lang.org/reference/behavior-considered-undefined.html).  According to [this crater failure](https://crater-reports.s3.amazonaws.com/pr-71274/try%2341997647ba6a77908f6ef64401414feb00bccf16/reg/text-0.0.4/log.txt), this zero-initializes an instance of `truetype::char_mapping::Encoding4`, for which 0 is not a valid value. The type seems defined by a macro so I could not track this down further.

Maybe a good replacement would be [`MaybeUninit`](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html), which tracks the possibility of uninitialized values at the type level to make sure the compiler does not make any false assumptions.

**Comment by IvanUkhov** [comment]
Thank you! It has been addressed.
