### ISSUE TITLE
name table parsing requires 1 too many bytes

### ISSUE THREAD

**Issue by vvuk** [bodoni/truetype#2]
When trying to parse a name table extracted from a font file, the parsing always fails due to underflow while reading.  In normal usage, the entire file is provided to `NamingTable::read`, but in this case, just the bytes of the name table itself are given.  I believe the issue is here: https://github.com/bodoni/truetype/blob/master/src/naming_table.rs#L124 -- that `+ 1` is incorrect; the length of the needed data buffer is just the max of `offset + length`.

**Comment by IvanUkhov** [comment]
Thanks for the issue! It looks very much plausible that the `+ 1` is an error. Would you mind opening a pull request?

**Comment by vvuk** [comment]
Yep, will do - I'm testing a few other issues as well, will make a PR
shortly.
